python preprocess.py -train_src /Users/chengxuyou/Documents/Study/FYP/HI-MAP/Multi-News-master/code/Multi-XScience/train.src \
                     -train_tgt /Users/chengxuyou/Documents/Study/FYP/HI-MAP/Multi-News-master/code/Multi-XScience/train.tgt \
                     -valid_src /Users/chengxuyou/Documents/Study/FYP/HI-MAP/Multi-News-master/code/Multi-XScience/val.src\
                     -valid_tgt /Users/chengxuyou/Documents/Study/FYP/HI-MAP/Multi-News-master/code/Multi-XScience/val.tgt \
                     -save_data newser_sent_500/newser_sents \
                     -src_seq_length 10000 \
                     -tgt_seq_length 10000 \
                     -src_seq_length_trunc 500 \
                     -tgt_seq_length_trunc 300 \
                     -dynamic_dict \
                     -share_vocab \
                     -max_shard_size 10000000
